GET http://localhost:3002/users

###
GET http://localhost:3000/users/3

###
GET http://localhost:3000/users/61729a6949e1294587b5ed6f

###
DELETE http://localhost:3000/users/61729a4949e1294587b5ed6a

###
DELETE http://localhost:3000/users/3

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstname": "John Doe",
  "lastname": "John Doe",
  "email": "test@test.com"
}
###
POST http://localhost:3002/users
Content-Type: application/json

{
  "nom": "John Doe",
  "prenom": "John Doe",
  "email": "test@test.com",
  "password": "test"
}
###
PUT http://localhost:3000/users/3
Content-Type: application/json

{
  "lastname": "John Durand",
  "email": ""
}

###
PUT http://localhost:3000/users/2
Content-Type: application/json

{
  "nom": "John Doe",
  "prenom": "John Doe",
  "email": "test@test.com",
  "password": "test"
}

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "prenom": "John Doe",
  "email": ""
}

###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "John Doe",
  "content": "John Doe",
  "authorId": 2
}

###
GET http://localhost:3000/articles


###
DELETE http://localhost:3000/articles/2

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

###
GET http://localhost:3000/