GET http://localhost:3000/users

###
GET http://localhost:3000/users/111111111111

###
GET http://localhost:3000/users/61729a6949e1294587b5ed6f

###
DELETE http://localhost:3000/users/61729a4949e1294587b5ed6a

###
DELETE http://localhost:3000/users/2

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstname": "John Doe",
  "lastname": "John Doe",
  "email": "test@test.com"
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "nom": "John Doe",
  "prenom": "John Doe",
  "email": ""
}
###
PUT http://localhost:3000/users/61729a6949e1294587b5ed6f
Content-Type: application/json

{
  "lastname": "John Durand",
  "email": ""
}

###
PUT http://localhost:3000/users/2
Content-Type: application/json

{
  "nom": "John Doe",
  "prenom": "John Doe",
  "email": ""
}

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "prenom": "John Doe",
  "email": ""
}